### ISSUE TITLE
LambDynamicLights support for throwable torch items

### ISSUE THREAD

**Issue by liqinyuan1211** [DanikingRD/ThrowableTorch#2]
They wrote a [document](https://github.com/LambdAurora/LambDynamicLights/blob/1.17/API.md) for how to implement this feature. 

I think this feature is useful while playing with both mods enabled.

**Comment by DanikingRD** [comment]
Done!
Here is the new update: https://www.curseforge.com/minecraft/mc-mods/throwabletorch-fabric/files/3827896
Thanks for your suggestion
